# Generated by Django 5.1.6 on 2025-03-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mongo_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
